name: Build and deploy Python app to Azure Web Apps

on:
  push:
    branches:
      - main
    paths:
      - 'fastapi/**'
      - 'streamlit/**'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - app-name: 'gentle-cat-back'
            app-path: 'fastapi/**'
            publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_51113BC899354501AB763EFF0F910854 }}
          - app-name: 'gentle-cat-front'
            app-path: 'streamlit/**'
            publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_82330B02A76142979BBFCA2AEA55D506 }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v1
        with:
          python-version: '3.9'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        run: pip install -r requirements.txt

      # Optional: Add step to run tests here (PyTest, Django test suites, etc.)
      - name: Zip artifact for deployment
        run: zip release.zip ./* -r

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v3
        with:
          name: python-app
          path: |
            release.zip
            !venv/

      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: 'Deploy to Azure Web App'
        if: contains(github.event.push.changes[0].files, matrix.app-path)
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ matrix.app-name }}
          slot-name: 'Production'
          publish-profile: ${{ matrix.publish-profile }}